### ISSUE TITLE
Cannot see TextInput or Send button

### ISSUE THREAD

**Issue by adamkearsley** [TheSmiths-Widgets/ts.chat2#14]
Hi.
I have installed the module and ran some tests.
I cannot seem to get the Text Input or send button to display at all.
I have tried everything!
The bar is shown at the bottom but its empty.
I have viewed my code, the widget and everything seems to be correct...

Also the bar at the bottom seems to be changing to red when setting the backgroundColor?
This is supposed to make the chat background red?
When i set backgroundColorBottomBar to red, nothing happens?
(SEE ATTACHMENT)

```
$.chat.init({
    messages: Alloy.Collections.discussion,
    validateSender: validateSender
});
```

```
<View class="chatContainer">
    <View id="chatWrapper">
        <Widget id="chat" src="ts.chat2"></Widget>
    </View>
</View>
```

<img width="838" alt="screen shot 2016-02-18 at 18 21 44" src="https://cloud.githubusercontent.com/assets/4035484/13153518/817e02ec-d66c-11e5-8af0-e4e32a2d5b3c.png">

**Comment by rpellerin** [comment]
Hi,

Thanks for feedback. Unfortunately, this widget is no longer supported.

Good luck
