### ISSUE TITLE
Any app example?

### ISSUE THREAD

**Issue by mcvendrell** [TheSmiths-Widgets/ts.chat2#4]
Hi.

I need to do a chat just right now and see this chat2 version. I tried ts.chat but no luck. Also trying to test this, but I was unable to make it run, I get always error with models: _Cannot read property 'models' of undefined_

Also the use of _Alloy.User.get('objectId')_ is strange in the widget code.

A full example app would be usefull

**Comment by PierreGUI** [comment]
![soon](https://s-media-cache-ak0.pinimg.com/236x/d8/5f/9e/d85f9e0756251a37423b6fd4e842b258.jpg)

**Comment by rpellerin** [comment]
Thanks, I'll probably do it this afternoon.

**Comment by mcvendrell** [comment]
Great, I'm doing my own tests with your code trying to figure out how all this works (I never used Models before) in an isolated app, but a working example app would be really useful

**Comment by rpellerin** [comment]
I added the branch 'sample'. See e5a8bff41925f02cf5081f989b87b7396ddd6f18

**Comment by mcvendrell** [comment]
Great I will check it and give you my impressions, thanks.

**Comment by chmiiller** [comment]
Wow, the sample is awesome! Thanks =)
Great job...really, great job lol
I'm also playing with this module: https://github.com/smclab/TiDAKeyboardControl to make the keyboard go down (on iOS) with the drag gesture, like whatsapp, skype, messenger and other apps do.

**Comment by KtorZ** [comment]
@chmiiller Nice module thanks !

**Comment by mcvendrell** [comment]
Hey Romain. Thank you for the example, works perfect. I will implement this chat in my current project and, once finished, I can help you with the documentation (the README to explain how to use it).

I didn't know that Backbone has been update and this needs 1.1.2, reading docs now.

One minor question: why the use of Alloy.User structure to check if message is from user? It seems that a simply "id" could work.

**Comment by rpellerin** [comment]
Sure, you help is welcomed :)

About Alloy.User, it's just a personal choice, we store our "current user" into this object but you can do differently of course.

**Comment by DouglasHennrich** [comment]
I'm getting this error when I tried to run the sample app:
`Script Error Couldn't find module: alloy/widgets/ts.chat2/controllers/widget for architecture: armv7`

Running on iOS

**Comment by rpellerin** [comment]
Did you try to update titanium and alloy and use the latest SDK? Upgrade your min-sdk in your app?

**Comment by PierreGUI** [comment]
@DouglasHennrich: Just a blind guess here: did you add the widget to you `config.json`'s dependencies ?
Also please create a new issue to ask about a different matter than the current one.

**Comment by mcvendrell** [comment]
Douglas, I can confirm that the demo works as expected on iOS and Android. 
My config is Ti 4.1.1GA, Maverick and Xcode 6

**Comment by DouglasHennrich** [comment]
@PierreGUI You are right! I was forgetting to add on `config.json` file

Thanks
