### ISSUE TITLE
Problems on iOS

### ISSUE THREAD

**Issue by mcvendrell** [TheSmiths-Widgets/ts.chat2#5]
Hi.

On Android all works fine, but I want to "embed" the chat on a NavigationWindow and I'm not able to "show" the navBar.

With the next code the navBar does't show:

```
<Alloy>
    <Window id="chatWin" title="Mensajes">
        <ActionBar onHomeIconItemSelected="close" />

        <LeftNavButton platform="ios">
            <Button onClick="close" />
        </LeftNavButton>

        <View top="60">
            <Widget id="chat" src="ts.chat2" />
        </View>
    </Window>
</Alloy>
```

If I remove the widget, the navBar is shown perfectly. 

Any clue?

**Comment by rpellerin** [comment]
No clue, sorry. Try to see if you can edit the style of the widget (directly in app/widget/ts.chat2/style) and let me know.

**Comment by mcvendrell** [comment]
Forget it, as always the problem was between the chair and the keyboard: I was opening the window twice. Working as expected, it is, really well.
